version: '3.6'

volumes:
  # logs:
  #   driver: local
  mysql_db:
    driver: local
    name: gp_mysql_db
  mongo_db:
    driver: local
    name: gp_mongo_db

services:
  # memcached:
  #   image: memcached:alpine
  #   container_name: gamersplane-memcached

  proxy:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: gamersplane-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../:/var/www

  api:
    build:
      context: ./
      dockerfile: Dockerfile-php
    container_name: gamersplane-api
    volumes:
      - ../:/var/www

  mysql:
    image: mysql:5.5
    container_name: gamersplane-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=p2HR1IQGF8c!A&amp;f&amp;
      - MYSQL_DATABASE=gamersplane
      - MYSQL_USER=gamersplane
      - MYSQL_PASSWORD=&amp;R6ivIqTS0b#wQ7e
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  mongo:
    build:
      context: ./mongo
    container_name: gamersplane-mongo
    volumes:
    - mongo_db:/data/db
