version: '3.6'

volumes:
  # logs:
  #   driver: local
  mysql_db:
    driver: local
    name: gpv1_mysql_db
  mongo_db:
    driver: local
    name: gpv1_mongo_db

services:
  # memcached:
  #   image: memcached:alpine
  #   container_name: gamersplane-memcached

  proxy:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: gpv1-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../:/var/www
    depends_on:
      - api

  api:
    build:
      context: ./
      dockerfile: Dockerfile-php
    container_name: gpv1-api
    volumes:
      - ../:/var/www
    depends_on:
      - mysql
      - mongo

  mysql:
    image: mysql:5.5
    container_name: gpv1-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=p2HR1IQGF8c!A&f&
      - MYSQL_DATABASE=gamersplane
      - MYSQL_USER=gamersplane
      - MYSQL_PASSWORD=&R6ivIqTS0b#wQ7e
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql_db:/var/lib/mysql

  mongo:
    build:
      context: ./mongo
    container_name: gpv1-mongo
    volumes:
      - mongo_db:/data/db
